apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: collapp-hpa
  namespace: collapp-dev-namespace
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    kind: Deployment
    name: collapp
    apiVersion: apps/v1

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75