spring.application.name=CollApp
server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/CollApp
spring.datasource.username=postgres
spring.datasource.password=sujal
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-circular-references=true
jwt.token.validity=3600
jwt.authorities.key=roles
jwt.secret=susususususususuususudfhalskdjfhasjdfhlakjsdhfajsdlfhaksdjhflakjsdhfalsjdkfhasjdfhlkasdf


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asur0825om@gmail.com
spring.mail.password=bhzbfhkmxcxdjhzh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
